---
prometheus_alert_rules:
  - alert: HostOutOfMemory
    expr: '(node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes < .10)'
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: Host out of memory (instance {% raw %}{{ $labels.instance }}{% endraw %})
      description: "Node memory is filling up (< 10% left)\n  VALUE = {% raw %}{{ $value }}{% endraw %}\n  LABELS = {% raw %}{{ $labels }}{% endraw %}"

  - alert: HostMemoryUnderMemoryPressure
    expr: '(rate(node_vmstat_pgmajfault[5m]) > 1000)'
    for: 0m
    labels:
      severity: warning
    annotations:
      summary: Host memory under memory pressure (instance {% raw %}{{ $labels.instance }}{% endraw %})
      description: "The node is under heavy memory pressure. High rate of loading memory pages from disk.\n  VALUE = {% raw %}{{ $value }}{% endraw %}\n  LABELS = {% raw %}{{ $labels }}{% endraw %}"

  - alert: HostMemoryIsUnderutilized
    expr: 'min_over_time(node_memory_MemFree_bytes[1w]) > node_memory_MemTotal_bytes * .8'
    for: 0m
    labels:
      severity: info
    annotations:
      summary: Host Memory is underutilized (instance {% raw %}{{ $labels.instance }}{% endraw %})
      description: "Node memory usage is < 20% for 1 week. Consider reducing memory space. (instance {% raw %}{{ $labels.instance }}{% endraw %})\n  VALUE = {% raw %}{{ $value }}{% endraw %}\n  LABELS = {% raw %}{{ $labels }}{% endraw %}"

  - alert: HostUnusualNetworkThroughputIn
    expr: '((rate(node_network_receive_bytes_total[5m]) / on(instance, device) node_network_speed_bytes) > .80)'
    for: 0m
    labels:
      severity: warning
    annotations:
      summary: Host unusual network throughput in (instance {% raw %}{{ $labels.instance }}{% endraw %})
      description: "Host receive bandwidth is high (>80%).\n  VALUE = {% raw %}{{ $value }}{% endraw %}\n  LABELS = {% raw %}{{ $labels }}{% endraw %}"

  - alert: HostUnusualNetworkThroughputOut
    expr: '((rate(node_network_transmit_bytes_total[5m]) / on(instance, device) node_network_speed_bytes) > .80)'
    for: 0m
    labels:
      severity: warning
    annotations:
      summary: Host unusual network throughput out (instance {% raw %}{{ $labels.instance }}{% endraw %})
      description: "Host transmit bandwidth is high (>80%)\n  VALUE = {% raw %}{{ $value }}{% endraw %}\n  LABELS = {% raw %}{{ $labels }}{% endraw %}"

  - alert: HostUnusualDiskReadRate
    expr: '(rate(node_disk_io_time_seconds_total[5m]) > .80)'
    for: 0m
    labels:
      severity: warning
    annotations:
      summary: Host unusual disk read rate (instance {% raw %}{{ $labels.instance }}{% endraw %})
      description: "Disk is too busy (IO wait > 80%)\n  VALUE = {% raw %}{{ $value }}{% endraw %}\n  LABELS = {% raw %}{{ $labels }}{% endraw %}"

  - alert: HostOutOfDiskSpace
    expr: '(node_filesystem_avail_bytes{fstype!~"^(fuse.*|tmpfs|cifs|nfs)"} / node_filesystem_size_bytes < .10 and on (instance, device, mountpoint) node_filesystem_readonly == 0)'
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: Host out of disk space (instance {% raw %}{{ $labels.instance }}{% endraw %})
      description: "Disk is almost full (< 10% left)\n  VALUE = {% raw %}{{ $value }}{% endraw %}\n  LABELS = {% raw %}{{ $labels }}{% endraw %}"

  - alert: HostDiskMayFillIn24Hours
    expr: 'predict_linear(node_filesystem_avail_bytes{fstype!~"^(fuse.*|tmpfs|cifs|nfs)"}[3h], 86400) <= 0 and node_filesystem_avail_bytes > 0'
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: Host disk may fill in 24 hours (instance {% raw %}{{ $labels.instance }}{% endraw %})
      description: "Filesystem will likely run out of space within the next 24 hours.\n  VALUE = {% raw %}{{ $value }}{% endraw %}\n  LABELS = {% raw %}{{ $labels }}{% endraw %}"

  - alert: HostOutOfInodes
    expr: '(node_filesystem_files_free / node_filesystem_files < .10 and ON (instance, device, mountpoint) node_filesystem_readonly == 0)'
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: Host out of inodes (instance {% raw %}{{ $labels.instance }}{% endraw %})
      description: "Disk is almost running out of available inodes (< 10% left)\n  VALUE = {% raw %}{{ $value }}{% endraw %}\n  LABELS = {% raw %}{{ $labels }}{% endraw %}"

  - alert: HostFilesystemDeviceError
    expr: 'node_filesystem_device_error{fstype!~"^(fuse.*|tmpfs|cifs|nfs)"} == 1'
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: Host filesystem device error (instance {% raw %}{{ $labels.instance }}{% endraw %})
      description: "Error stat-ing the {% raw %}{{ $labels.mountpoint }}{% endraw %} filesystem\n  VALUE = {% raw %}{{ $value }}{% endraw %}\n  LABELS = {% raw %}{{ $labels }}{% endraw %}"

  - alert: HostInodesMayFillIn24Hours
    expr: 'predict_linear(node_filesystem_files_free{fstype!~"^(fuse.*|tmpfs|cifs|nfs)"}[1h], 86400) <= 0 and node_filesystem_files_free > 0'
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: Host inodes may fill in 24 hours (instance {% raw %}{{ $labels.instance }}{% endraw %})
      description: "Filesystem will likely run out of inodes within the next 24 hours at current write rate\n  VALUE = {% raw %}{{ $value }}{% endraw %}\n  LABELS = {% raw %}{{ $labels }}{% endraw %}"

  - alert: HostUnusualDiskReadLatency
    expr: '(rate(node_disk_read_time_seconds_total[1m]) / rate(node_disk_reads_completed_total[1m]) > 0.1 and rate(node_disk_reads_completed_total[1m]) > 0)'
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: Host unusual disk read latency (instance {% raw %}{{ $labels.instance }}{% endraw %})
      description: "Disk latency is growing (read operations > 100ms)\n  VALUE = {% raw %}{{ $value }}{% endraw %}\n  LABELS = {% raw %}{{ $labels }}{% endraw %}"

  - alert: HostUnusualDiskWriteLatency
    expr: '(rate(node_disk_write_time_seconds_total[1m]) / rate(node_disk_writes_completed_total[1m]) > 0.1 and rate(node_disk_writes_completed_total[1m]) > 0)'
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: Host unusual disk write latency (instance {% raw %}{{ $labels.instance }}{% endraw %})
      description: "Disk latency is growing (write operations > 100ms)\n  VALUE = {% raw %}{{ $value }}{% endraw %}\n  LABELS = {% raw %}{{ $labels }}{% endraw %}"

  - alert: HostHighCpuLoad
    expr: '1 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[5m]))) > .80'
    for: 10m
    labels:
      severity: warning
    annotations:
      summary: Host high CPU load (instance {% raw %}{{ $labels.instance }}{% endraw %})
      description: "CPU load is > 80%\n  VALUE = {% raw %}{{ $value }}{% endraw %}\n  LABELS = {% raw %}{{ $labels }}{% endraw %}"

  - alert: HostCpuIsUnderutilized
    expr: '(min by (instance) (rate(node_cpu_seconds_total{mode="idle"}[1h]))) > 0.8'
    for: 1w
    labels:
      severity: info
    annotations:
      summary: Host CPU is underutilized (instance {% raw %}{{ $labels.instance }}{% endraw %})
      description: "CPU load has been < 20% for 1 week. Consider reducing the number of CPUs.\n  VALUE = {% raw %}{{ $value }}{% endraw %}\n  LABELS = {% raw %}{{ $labels }}{% endraw %}"

  - alert: HostCpuStealNoisyNeighbor
    expr: 'avg by(instance) (rate(node_cpu_seconds_total{mode="steal"}[5m])) * 100 > 10'
    for: 0m
    labels:
      severity: warning
    annotations:
      summary: Host CPU steal noisy neighbor (instance {% raw %}{{ $labels.instance }}{% endraw %})
      description: "CPU steal is > 10%. A noisy neighbor is killing VM performances or a spot instance may be out of credit.\n  VALUE = {% raw %}{{ $value }}{% endraw %}\n  LABELS = {% raw %}{{ $labels }}{% endraw %}"

  - alert: HostCpuHighIowait
    expr: 'avg by (instance) (rate(node_cpu_seconds_total{mode="iowait"}[5m])) > .10'
    for: 0m
    labels:
      severity: warning
    annotations:
      summary: Host CPU high iowait (instance {% raw %}{{ $labels.instance }}{% endraw %})
      description: "CPU iowait > 10%. Your CPU is idling waiting for storage to respond.\n  VALUE = {% raw %}{{ $value }}{% endraw %}\n  LABELS = {% raw %}{{ $labels }}{% endraw %}"

  - alert: HostUnusualDiskIo
    expr: 'rate(node_disk_io_time_seconds_total[5m]) > 0.8'
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: Host unusual disk IO (instance {% raw %}{{ $labels.instance }}{% endraw %})
      description: "Disk usage >80%. Check storage for issues or increase IOPS capabilities. Check storage for issues.\n  VALUE = {% raw %}{{ $value }}{% endraw %}\n  LABELS = {% raw %}{{ $labels }}{% endraw %}"

  - alert: HostContextSwitchingHigh
    expr: '(rate(node_context_switches_total[15m])/count without(mode,cpu) (node_cpu_seconds_total{mode="idle"})) / (rate(node_context_switches_total[1d])/count without(mode,cpu) (node_cpu_seconds_total{mode="idle"})) > 2'
    for: 0m
    labels:
      severity: warning
    annotations:
      summary: Host context switching high (instance {% raw %}{{ $labels.instance }}{% endraw %})
      description: "Context switching is growing on the node (twice the daily average during the last 15m)\n  VALUE = {% raw %}{{ $value }}{% endraw %}\n  LABELS = {% raw %}{{ $labels }}{% endraw %}"

  - alert: HostSwapIsFillingUp
    expr: '((1 - (node_memory_SwapFree_bytes / node_memory_SwapTotal_bytes)) * 100 > 80)'
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: Host swap is filling up (instance {% raw %}{{ $labels.instance }}{% endraw %})
      description: "Swap is filling up (>80%)\n  VALUE = {% raw %}{{ $value }}{% endraw %}\n  LABELS = {% raw %}{{ $labels }}{% endraw %}"

  - alert: HostSystemdServiceCrashed
    expr: '(node_systemd_unit_state{state="failed"} == 1)'
    for: 0m
    labels:
      severity: warning
    annotations:
      summary: Host systemd service crashed (instance {% raw %}{{ $labels.instance }}{% endraw %})
      description: "systemd service crashed\n  VALUE = {% raw %}{{ $value }}{% endraw %}\n  LABELS = {% raw %}{{ $labels }}{% endraw %}"

  - alert: HostPhysicalComponentTooHot
    expr: 'node_hwmon_temp_celsius > node_hwmon_temp_max_celsius'
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: Host physical component too hot (instance {% raw %}{{ $labels.instance }}{% endraw %})
      description: "Physical hardware component too hot\n  VALUE = {% raw %}{{ $value }}{% endraw %}\n  LABELS = {% raw %}{{ $labels }}{% endraw %}"

  - alert: HostNodeOvertemperatureAlarm
    expr: '((node_hwmon_temp_crit_alarm_celsius == 1) or (node_hwmon_temp_alarm == 1))'
    for: 0m
    labels:
      severity: critical
    annotations:
      summary: Host node overtemperature alarm (instance {% raw %}{{ $labels.instance }}{% endraw %})
      description: "Physical node temperature alarm triggered\n  VALUE = {% raw %}{{ $value }}{% endraw %}\n  LABELS = {% raw %}{{ $labels }}{% endraw %}"

  - alert: HostSoftwareRaidInsufficientDrives
    expr: '((node_md_disks_required - on(device, instance) node_md_disks{state="active"}) > 0)'
    for: 0m
    labels:
      severity: critical
    annotations:
      summary: Host software RAID insufficient drives (instance {% raw %}{{ $labels.instance }}{% endraw %})
      description: "MD RAID array {% raw %}{{ $labels.device }}{% endraw %} on {% raw %}{{ $labels.instance }}{% endraw %} has insufficient drives remaining.\n  VALUE = {% raw %}{{ $value }}{% endraw %}\n  LABELS = {% raw %}{{ $labels }}{% endraw %}"

  - alert: HostSoftwareRaidDiskFailure
    expr: '(node_md_disks{state="failed"} > 0)'
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: Host software RAID disk failure (instance {% raw %}{{ $labels.instance }}{% endraw %})
      description: "MD RAID array {% raw %}{{ $labels.device }}{% endraw %} on {% raw %}{{ $labels.instance }}{% endraw %} needs attention.\n  VALUE = {% raw %}{{ $value }}{% endraw %}\n  LABELS = {% raw %}{{ $labels }}{% endraw %}"

  - alert: HostKernelVersionDeviations
    expr: 'changes(node_uname_info[1h]) > 0'
    for: 0m
    labels:
      severity: info
    annotations:
      summary: Host kernel version deviations (instance {% raw %}{{ $labels.instance }}{% endraw %})
      description: "Kernel version for {% raw %}{{ $labels.instance }}{% endraw %} has changed.\n  VALUE = {% raw %}{{ $value }}{% endraw %}\n  LABELS = {% raw %}{{ $labels }}{% endraw %}"

  - alert: HostOomKillDetected
    expr: '(increase(node_vmstat_oom_kill[1m]) > 0)'
    for: 0m
    labels:
      severity: warning
    annotations:
      summary: Host OOM kill detected (instance {% raw %}{{ $labels.instance }}{% endraw %})
      description: "OOM kill detected\n  VALUE = {% raw %}{{ $value }}{% endraw %}\n  LABELS = {% raw %}{{ $labels }}{% endraw %}"

  - alert: HostEdacCorrectableErrorsDetected
    expr: '(increase(node_edac_correctable_errors_total[1m]) > 0)'
    for: 0m
    labels:
      severity: info
    annotations:
      summary: Host EDAC Correctable Errors detected (instance {% raw %}{{ $labels.instance }}{% endraw %})
      description: "Host {% raw %}{{ $labels.instance }}{% endraw %} has had {% raw %}{{ printf \"%.0f\" $value }}{% endraw %} correctable memory errors reported by EDAC in the last 5 minutes.\n  VALUE = {% raw %}{{ $value }}{% endraw %}\n  LABELS = {% raw %}{{ $labels }}{% endraw %}"

  - alert: HostEdacUncorrectableErrorsDetected
    expr: '(node_edac_uncorrectable_errors_total > 0)'
    for: 0m
    labels:
      severity: warning
    annotations:
      summary: Host EDAC Uncorrectable Errors detected (instance {% raw %}{{ $labels.instance }}{% endraw %})
      description: "Host {% raw %}{{ $labels.instance }}{% endraw %} has had {% raw %}{{ printf \"%.0f\" $value }}{% endraw %} uncorrectable memory errors reported by EDAC in the last 5 minutes.\n  VALUE = {% raw %}{{ $value }}{% endraw %}\n  LABELS = {% raw %}{{ $labels }}{% endraw %}"

  - alert: HostNetworkReceiveErrors
    expr: '(rate(node_network_receive_errs_total[2m]) / rate(node_network_receive_packets_total[2m]) > 0.01)'
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: Host Network Receive Errors (instance {% raw %}{{ $labels.instance }}{% endraw %})
      description: "Host {% raw %}{{ $labels.instance }}{% endraw %} interface {% raw %}{{ $labels.device }}{% endraw %} has encountered {% raw %}{{ printf \"%.0f\" $value }}{% endraw %} receive errors in the last two minutes.\n  VALUE = {% raw %}{{ $value }}{% endraw %}\n  LABELS = {% raw %}{{ $labels }}{% endraw %}"

  - alert: HostNetworkTransmitErrors
    expr: '(rate(node_network_transmit_errs_total[2m]) / rate(node_network_transmit_packets_total[2m]) > 0.01)'
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: Host Network Transmit Errors (instance {% raw %}{{ $labels.instance }}{% endraw %})
      description: "Host {% raw %}{{ $labels.instance }}{% endraw %} interface {% raw %}{{ $labels.device }}{% endraw %} has encountered {% raw %}{{ printf \"%.0f\" $value }}{% endraw %} transmit errors in the last two minutes.\n  VALUE = {% raw %}{{ $value }}{% endraw %}\n  LABELS = {% raw %}{{ $labels }}{% endraw %}"

  - alert: HostNetworkBondDegraded
    expr: '((node_bonding_active - node_bonding_slaves) != 0)'
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: Host Network Bond Degraded (instance {% raw %}{{ $labels.instance }}{% endraw %})
      description: "Bond \"{% raw %}{{ $labels.device }}{% endraw %}\" degraded on \"{% raw %}{{ $labels.instance }}{% endraw %}\".\n  VALUE = {% raw %}{{ $value }}{% endraw %}\n  LABELS = {% raw %}{{ $labels }}{% endraw %}"

  - alert: HostConntrackLimit
    expr: '(node_nf_conntrack_entries / node_nf_conntrack_entries_limit > 0.8)'
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: Host conntrack limit (instance {% raw %}{{ $labels.instance }}{% endraw %})
      description: "The number of conntrack is approaching limit\n  VALUE = {% raw %}{{ $value }}{% endraw %}\n  LABELS = {% raw %}{{ $labels }}{% endraw %}"

  - alert: HostClockSkew
    expr: '((node_timex_offset_seconds > 0.05 and deriv(node_timex_offset_seconds[5m]) >= 0) or (node_timex_offset_seconds < -0.05 and deriv(node_timex_offset_seconds[5m]) <= 0))'
    for: 10m
    labels:
      severity: warning
    annotations:
      summary: Host clock skew (instance {% raw %}{{ $labels.instance }}{% endraw %})
      description: "Clock skew detected. Clock is out of sync. Ensure NTP is configured correctly on this host.\n  VALUE = {% raw %}{{ $value }}{% endraw %}\n  LABELS = {% raw %}{{ $labels }}{% endraw %}"

  - alert: HostClockNotSynchronising
    expr: '(min_over_time(node_timex_sync_status[1m]) == 0 and node_timex_maxerror_seconds >= 16)'
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: Host clock not synchronising (instance {% raw %}{{ $labels.instance }}{% endraw %})
      description: "Clock not synchronising. Ensure NTP is configured on this host.\n  VALUE = {% raw %}{{ $value }}{% endraw %}\n  LABELS = {% raw %}{{ $labels }}{% endraw %}"
