$ANSIBLE_VAULT;1.1;AES256
64653334626464306338356339636537356435616232636332653930393061623438626466356138
6536393863633462393065333135626665623065626163320a666265383833363735643532316134
38653963393464656662623931396138633437346365633961643434373437663035656331306564
3030643562343038640a663836656464343138356534303662306236313635353830313432616431
64656263633662343166656164633437663234633534623765396363653961356663353366336531
61663466383037653530636235393837366361346534366161643262623732326566636230323731
31333735386632336336616439313261663438653534393634346537666663373366346136363863
66666364363235336231653966646661373730326238613635613831653365323766393266643762
31663233366637363062393963343165653963643365333936356638313334303333363637323134
31633731313365653331383064653239383761343030663462616136313332633334653034616166
38316439623337653361313439386530313030336462653438663833633034636537323233336431
31666435393665326232353165316539653861356462336632303839663630623765316636666135
38376539313831656635343064666338633564356165396165386332353039303539373033323935
33653931303130376137383562646235626562616161343331393039393266616231623639373762
643439383964333964323132383363303636
