$ANSIBLE_VAULT;1.1;AES256
38636335316439653366303731373033623236623334393961363636626262336138623736376562
3066623830303165633931633435626565396334663162640a643336333966313238313639366532
64643464336130666637333130646235386563323762366365336463386132643233386439653163
3530653037343961370a393439383534626266316337613031376566663433373137326136616532
35336338363161623537653038313838356461393637353133626262666435303462336232333631
37336165383864653239656264353638623166643138383831386339366535613638336161616631
66373536613436656235373936356235623462346566613762313761643930633636633132626533
32636364663761383730636438343431666664636666656565383632643339343062656163666164
31633462336633663534623762653632323436303861336562383766393966353835386563626430
65613738346361386566336434353033646231343565353534363934396665313561653631666436
39346265316361353666656263643162656639643761333337663337643063303066626336313064
62393863316339376462616661643164643333353735336163636462356161373635313235373537
32653465336565363132646466626433643263363333396635663931303230366438396666393434
65373532313366393836313531323139343262663432306465396237613439333864656539636132
356366356237666466663934626134313761
