$ANSIBLE_VAULT;1.1;AES256
33323463303764336139353161323539643066396461636631623465653665396262306435383737
6338633531326565663431626161333430363038663161390a356265623633343164633536396639
35623362363965663261373737356664623633373930363839626163363966633232333730656466
3633646433363464300a373932376530636231386439663738333532313266303263396566363739
34336136633063613531363438396364323931333836623831396234666437383238353761393933
66353363616535613761653663336264356261653165366635633331356539313734623761643534
62346331356239363737613936666532343162393432643761306337363034323336366137343362
36643735613532616631353338643566613031323737633263633832653163303963623631663536
62363665653164646363653331393562613330366432636630313330633362313064383363316639
3065626362356239363663653661323535656635316366663034
