$ANSIBLE_VAULT;1.1;AES256
38653635306164393030303339663437323161306532616331353463633636666663343735373835
3532653530643532386163333866356261653531626133360a623937626437313739343034633430
64633462363538316538386231363933333136386361633738393038333939666537373431316164
6638653663323532380a666631356539326532383466373632613564666364663961613165386662
39323639363033653134333731356561643039633730306366316633313234663138353935323130
37326639663034626163343365303164313563393632323535343531323736613231633863616632
65623563666166363665373631636464336533633736356432393962303730613563366631356539
66316534326539373631343936346138666131376362623061633432656634626364353339643032
36306364643132396630343632336435613530323038353731663132373439616363633165623739
37323830393336366365613933636335373939353538363231643639333332356131303334613961
39343332646239633365333463336662343065643833646437656530373237343937383235346636
62393838306166326532373339643962373836363739623864383434313037376534663238666362
33366131366136383832636233643962613863373835306661396138393333353865376565613631
65623039656435633464656564333030356233336239316431316138643731323962326362626566
32623361316264353962383636383231323330663939663330623038663233616265656339336234
30646436633739626161333735363730373534346231373265653964333830323733363632333131
65623230616435646261303632663735623533376261393432366130346339333934353531323065
32633962303031613864316164316462393563356335636465343236303638666339363839656630
323837386537646537386332616435366635
