$ANSIBLE_VAULT;1.1;AES256
34306233393232326566316230386162363830383830393738623866333939643537633331393366
6166373237383063336231343861343336396335343231320a346130366532636465336330663063
30323033353163313832656636386431313231393534336566373334393534616331666330346166
6564633766636236330a393266393866306638663731366637303632383339353866393434346136
33383730366438306366653163626334393130366438333638396236326562306233616131646365
36313037613265613561333066343565396432616335373032386338643930623135653038363434
32333630633638346335396366636666616638353032656139653064646236346262626232623431
33316137623565303539613036643962656439626134626538303237316239653238343332343066
6162
