---
- name: Ensure shared Docker network is present
  when: docker_shared_network_create | default(true)
  community.docker.docker_network:
    name: "{{ docker_shared_network_name }}"
    driver: "{{ docker_shared_network_driver }}"
    attachable: "{{ docker_shared_network_attachable }}"
    enable_ipv6: "{{ docker_shared_network_enable_ipv6 }}"
    ipam_config: "{{ docker_shared_network_ipam_config }}"
    labels: "{{ docker_shared_network_labels }}"
