---
gemi2api_enable: false
gemi2api_image: bernylinville/gemi2api
gemi2api_image_tag: latest
gemi2api_container_name: gemi2api
gemi2api_bind_address: 127.0.0.1
gemi2api_bind_port: 8000
gemi2api_container_port: 8000
gemi2api_network_name: "{{ docker_shared_network_name }}"
gemi2api_pull: true
gemi2api_restart_policy: unless-stopped
gemi2api_env_defaults:
  SECURE_1PSID: ""
  SECURE_1PSIDTS: ""
  API_KEY: ""
  ENABLE_THINKING: "true"
gemi2api_env_overrides: {}
gemi2api_labels: {}
gemi2api_state: started
