---
docker_shared_network_name: proxy_net
docker_shared_network_subnet: "10.203.57.0/24"
docker_shared_network_gateway: "10.203.57.1"
docker_shared_network_driver: bridge
docker_shared_network_attachable: true
docker_shared_network_enable_ipv6: false
docker_shared_network_labels: {}
docker_shared_network_create: true
docker_shared_network_ipam_config:
  - subnet: "{{ docker_shared_network_subnet }}"
    gateway: "{{ docker_shared_network_gateway }}"
