$ANSIBLE_VAULT;1.1;AES256
64613330643431646237336635666266643938343137653163623564643537353334366561376564
6466313731336264653433633235656632626632643535660a323431626366373237396564373832
38376134343662323835613439623135323732376461633664373165363036316530626531646232
6238346232643630640a306534383138393530653461613635353535626332383637313836366332
33323831333561623030643461336330356331386139366137353133303237626262393262363933
37636566623838616137383536333931666633393732383066613362656537643836653836343634
32383664386134316138643738343765646533623135633036626538393432333337376533383431
33653731333934343564646436353661393638316435636564653666336536656565663534383937
31393265356131336261643861363262626665373864393031303639643930663062633061666432
36623532313333336261303736353162343063373131363861656531323366303966333164633066
61323733643837653038643466656431663931653530303138353265306336373366633661343364
32306632323237653935623466363766663431383333373539383136393931396133313130336366
6661
