---
- name: Bootstrap Debian hosts before role convergence
  hosts: vps
  # become: true
  gather_facts: false

  pre_tasks:
    - name: Gather facts after Python is present
      ansible.builtin.setup:
      tags: [facts]

    - name: Install Python dependencies for Docker modules
      ansible.builtin.apt:
        name:
          - python3-requests
          - python3-docker
          # - openssh-server
        state: present
        update_cache: true
      become: true
      tags: [deps]

    - name: Change hostname
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"
      become: true

    - name: Ensure hostname resolves in /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: '^127\.0\.1\.1\s+'
        line: "127.0.1.1 {{ inventory_hostname }}"
        insertafter: '^127\.0\.0\.1.*'
        state: present
      become: true
      tags: [notest]

  roles:
    - role: geerlingguy.ntp
      become: true
    - role: geerlingguy.security
      become: true
    # - geerlingguy.firewall
    - role: geerlingguy.docker
      become: true
    - role: docker_custom
    - role: traefik
    - role: gemi2api
    - role: lobe_chat
    - role: axonhub
    - role: new_api
    - role: prometheus.prometheus.node_exporter
      become: true
    # - role: prometheus.prometheus.prometheus
    #   when: prometheus_enabled | default(false)
    # - role: prometheus.prometheus.alertmanager
    #   when: alertmanager_enabled | default(false)
    # - role: grafana.grafana.grafana
    #   when: grafana_enabled | default(false)
    # - role: cloudflared
    #   when: cloudflared_enabled | default(false)
