---
- name: Bootstrap Debian hosts before role convergence
  hosts: vps
  become: true
  gather_facts: false

  pre_tasks:
    - name: Gather facts after Python is present
      ansible.builtin.setup:
      tags: [facts]

    - name: Install Python dependencies for Docker modules
      ansible.builtin.apt:
        name:
          - python3-requests
          - python3-docker
          # - openssh-server
        state: present
        update_cache: true
      tags: [deps]

  roles:
    - geerlingguy.security
    - geerlingguy.firewall
    - geerlingguy.docker
    - docker_shared_network
    - prometheus.prometheus.node_exporter
    - role: prometheus.prometheus.prometheus
      when: prometheus_enabled | default(false)
    - role: prometheus.prometheus.alertmanager
      when: alertmanager_enabled | default(false)
    - role: grafana.grafana.grafana
      when: grafana_enabled | default(false)
    - role: cloudflared
      when: cloudflared_enabled | default(false)
