---
- name: Bootstrap Debian hosts before role convergence
  hosts: vps
  become: true
  gather_facts: false

  pre_tasks:
    - name: Gather facts after Python is present
      ansible.builtin.setup:
      tags: [facts]

    - name: Install Python dependencies for Docker modules
      ansible.builtin.apt:
        name:
          - python3-requests
          - python3-docker
          # - openssh-server
        state: present
        update_cache: true
      tags: [deps]

  roles:
    - geerlingguy.security
    - geerlingguy.firewall
    - geerlingguy.docker
