---
beszel_agent_enable: false
beszel_agent_image: henrygd/beszel-agent
beszel_agent_image_tag: "0.17.0"
beszel_agent_container_name: beszel-agent
beszel_agent_pull: true
beszel_agent_restart_policy: unless-stopped
beszel_agent_state: started
beszel_agent_network_mode: host
beszel_agent_data_directory: /opt/beszel-agent
beszel_agent_docker_socket_path: /var/run/docker.sock
beszel_agent_extra_volumes: []

beszel_agent_listen_port: "45876"
beszel_agent_hub_scheme: http
beszel_agent_hub_host: ""
beszel_agent_hub_port: 8090

beszel_agent_env_defaults:
  LISTEN: "{{ beszel_agent_listen_port }}"
  HUB_URL: "{{ beszel_agent_hub_scheme }}://{{ beszel_agent_hub_host }}:{{ beszel_agent_hub_port }}"
  KEY: ""
  TOKEN: ""

beszel_agent_env_overrides: {}
beszel_agent_labels: {}
