$ANSIBLE_VAULT;1.1;AES256
36646336353335343964613762323238636439373834306363653665393432376139366161396432
3066306230636263346233653730373633323335333866370a613434663635316531653333666639
63633263396637373338623863623264366262643337653834356261383831386538353063333064
6232313332626436630a353361623431653236373832623636306539323366636164396431373461
65353331663332613864353539643664653038623630306533313839636637376166636239373139
33646330646432396332636637643530366238376162373433363165613139343835626662383035
37343263323262633834613636313335363831653334333663393831646662376431396638356636
64346338663830343137323464383739303233626236303038373131316262393133633830656539
62366130333938656330656134313763373532643165623061623139313761306330613235616264
37306565613039663262646563623237666162643636393561373639303266353766376466316139
65313362363634336366336430343030646438636462616332336430653838323865303332373239
31343662346430643937653938636663303135356235313364366665373437333233613137316639
65363665626464646262346530396639393365383336613963656266356334353834343965343062
63336164323535656163613066316461343163623130333539633662633764663537613531306430
39373137663531396361353338353435373861313138313365383163613462353635613134653662
36623632653539313936396137393635663164353665346130616163613061373936336133303934
36316431326135616436666262383938326230303164636633386666303365636363
