$ANSIBLE_VAULT;1.1;AES256
38353033336463653538363736373862663332313536376537653933376536663834336531643839
3264636535343231623031636433633834646536396439650a666664616164333530623339653539
63316433393031636339313933646333363366386430346666333731653537656466363838656639
6439643530346137630a633864666166626565393035356135363232626162363032363136373133
34643435356164613336303263646533633465303437663066336561386536333235396365346665
35366264356165396131306238626464646438363761666464396334646432653338343962323565
65376534623032633265393132333762333636333462623336366336346564366133663936373432
32323037306232346263316139353137303765323636616464346265666562636432333230396161
65393237323731616662316436333931643038303266343061383861383065623962333733333966
36343632386532626633653238663130343062373836666336316365633539306464386634643464
62353736626238396638306166323630393631306361303135353761306364633937643632343462
36333662366663613233336162366362356330303631616437323661313033653135343834643763
63313933653633623562663837366663343830623832363734333461316435353338386435643664
63333866653863616137613866366664613966313365643962643134386236653938666265353236
626434616264663331633730626434663764
