---
ansible_python_interpreter: /usr/bin/python3
ansible_ssh_private_key_file: "{{ lookup('env', 'ANSIBLE_SSH_KEY_PATH') | default('~/.ssh/id_ed25519', true) }}"
ansible_ssh_common_args: >-
  -o ConnectionAttempts=6
  -o ConnectTimeout=20
domain_name: devopsthink.org
nas_tailscale_ip: 100.80.43.37

cloudflared_tunnel_domain_name: "{{ domain_name }}"

beszel_agent_hub_host: "{{ nas_tailscale_ip }}"
