---
ansible_python_interpreter: /usr/bin/python3
ansible_ssh_private_key_file: "{{ lookup('env', 'ANSIBLE_SSH_KEY_PATH') | default('~/.ssh/id_ed25519', true) }}"
domain_name: devopsthink.org
cloudflared_tunnel_domain_name: "{{ domain_name }}"
